using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace DungeonBuilder.M0.Gameplay.DungeonSpatial
{
    public enum SpatialMigrationJournalStage { DescriptorPinned=1, BackupVerified=2, CandidateVerified=3, Replaced=4, DurableVerified=5, Finalized=6, OriginalRestored=7 }
    public sealed class SpatialMigrationJournal
    {
        public SpatialMigrationJournal(int journalSchemaVersion,SpatialMigrationInputDescriptor descriptor,string descriptorFingerprintSha256,string transactionIdentitySha256,string transactionId,string relativeJournalFilename,string relativeOriginalBackupFilename,string relativeCandidateStagingFilename,string relativeFinalizedReceiptFilename,string originalPayloadSha256,string backupPayloadSha256,string expectedCandidateSha256,SpatialMigrationJournalStage stage)
        {JournalSchemaVersion=journalSchemaVersion;Descriptor=descriptor;DescriptorFingerprintSha256=descriptorFingerprintSha256;TransactionIdentitySha256=transactionIdentitySha256;TransactionId=transactionId;RelativeJournalFilename=relativeJournalFilename;RelativeOriginalBackupFilename=relativeOriginalBackupFilename;RelativeCandidateStagingFilename=relativeCandidateStagingFilename;RelativeFinalizedReceiptFilename=relativeFinalizedReceiptFilename;OriginalPayloadSha256=originalPayloadSha256;BackupPayloadSha256=backupPayloadSha256;ExpectedCandidateSha256=expectedCandidateSha256;Stage=stage;}
        public int JournalSchemaVersion{get;} public SpatialMigrationInputDescriptor Descriptor{get;} public string DescriptorFingerprintSha256{get;} public string TransactionIdentitySha256{get;} public string TransactionId{get;} public string RelativeJournalFilename{get;} public string RelativeOriginalBackupFilename{get;} public string RelativeCandidateStagingFilename{get;} public string RelativeFinalizedReceiptFilename{get;} public string OriginalPayloadSha256{get;} public string BackupPayloadSha256{get;} public string ExpectedCandidateSha256{get;} public SpatialMigrationJournalStage Stage{get;}
    }
    public static class SpatialMigrationJournalContracts
    {
        private static readonly string[] Names={"JournalSchemaVersion","Descriptor","DescriptorFingerprintSha256","TransactionIdentitySha256","TransactionId","RelativeJournalFilename","RelativeOriginalBackupFilename","RelativeCandidateStagingFilename","RelativeFinalizedReceiptFilename","OriginalPayloadSha256","BackupPayloadSha256","ExpectedCandidateSha256","Stage"};
        public static SpatialContractResult<byte[]> Serialize(SpatialMigrationJournal j,SpatialSerializedInputLimits limits)
        {
            var issues=new List<SpatialContractIssue>();Validate(j,limits,issues);if(issues.Count!=0)return new SpatialContractResult<byte[]>(null,issues);byte[] descriptor=SpatialMigrationDescriptorContracts.Serialize(j.Descriptor,limits).Value;var b=new StringBuilder();b.Append('{');AddI(b,Names[0],j.JournalSchemaVersion,true);b.Append(',');ContractJson.String(b,Names[1]);b.Append(':').Append(Encoding.UTF8.GetString(descriptor));AddS(b,Names[2],j.DescriptorFingerprintSha256);AddS(b,Names[3],j.TransactionIdentitySha256);AddS(b,Names[4],j.TransactionId);AddS(b,Names[5],j.RelativeJournalFilename);AddS(b,Names[6],j.RelativeOriginalBackupFilename);AddS(b,Names[7],j.RelativeCandidateStagingFilename);AddNullable(b,Names[8],j.RelativeFinalizedReceiptFilename);AddS(b,Names[9],j.OriginalPayloadSha256);AddNullable(b,Names[10],j.BackupPayloadSha256);AddNullable(b,Names[11],j.ExpectedCandidateSha256);AddI(b,Names[12],(int)j.Stage);b.Append('}');byte[] bytes=ContractJson.Bytes(b.ToString());if(bytes.Length>limits.MaximumInputBytes)issues.Add(SpatialContractIssue.InputByteLimitExceeded);return new SpatialContractResult<byte[]>(issues.Count==0?bytes:null,issues);
        }
        public static SpatialContractResult<SpatialMigrationJournal> Parse(byte[] bytes,SpatialSerializedInputLimits limits)
        {
            var issues=new List<SpatialContractIssue>();if(!ContractJson.TryParse(bytes,limits,issues,out ContractJsonNode n))return new SpatialContractResult<SpatialMigrationJournal>(null,issues);if(!ContractJson.Shape(n,Names,issues))return new SpatialContractResult<SpatialMigrationJournal>(null,issues);if(!ContractJson.Int(ContractJson.Field(n,0),out int version)||!ContractJson.Int(ContractJson.Field(n,12),out int stage))issues.Add(SpatialContractIssue.WrongFieldType);
            var descriptor=SpatialMigrationDescriptorContracts.Parse(ContractJson.Bytes(ContractJson.Compact(ContractJson.Field(n,1))),limits);if(!descriptor.IsValid)issues.Add(SpatialContractIssue.InvalidField);string[] s=new string[12];for(int i=2;i<=7;i++)if(!ContractJson.Str(ContractJson.Field(n,i),out s[i]))issues.Add(SpatialContractIssue.WrongFieldType);for(int i=8;i<=11;i++){ContractJsonNode v=ContractJson.Field(n,i);if(v.Kind==ContractJsonKind.Null)s[i]=null;else if(!ContractJson.Str(v,out s[i]))issues.Add(SpatialContractIssue.WrongFieldType);}
            if(issues.Count!=0)return new SpatialContractResult<SpatialMigrationJournal>(null,issues);var j=new SpatialMigrationJournal(version,descriptor.Value,s[2],s[3],s[4],s[5],s[6],s[7],s[8],s[9],s[10],s[11],(SpatialMigrationJournalStage)stage);Validate(j,limits,issues);if(issues.Count==0){var again=Serialize(j,limits);if(!again.IsValid||!bytes.SequenceEqual(again.Value))issues.Add(SpatialContractIssue.NonCanonicalBytes);}return new SpatialContractResult<SpatialMigrationJournal>(issues.Count==0?j:null,issues);
        }
        public static bool IsAllowedTransition(SpatialMigrationJournalStage from,SpatialMigrationJournalStage to)
        {
            if(!Enum.IsDefined(typeof(SpatialMigrationJournalStage),from)||!Enum.IsDefined(typeof(SpatialMigrationJournalStage),to)||from==SpatialMigrationJournalStage.Finalized||from==SpatialMigrationJournalStage.OriginalRestored)return false;
            if(from==SpatialMigrationJournalStage.DescriptorPinned)return to==SpatialMigrationJournalStage.BackupVerified;
            if(from==SpatialMigrationJournalStage.BackupVerified)return to==SpatialMigrationJournalStage.CandidateVerified||to==SpatialMigrationJournalStage.OriginalRestored;
            if(from==SpatialMigrationJournalStage.CandidateVerified)return to==SpatialMigrationJournalStage.Replaced||to==SpatialMigrationJournalStage.OriginalRestored;
            if(from==SpatialMigrationJournalStage.Replaced)return to==SpatialMigrationJournalStage.DurableVerified||to==SpatialMigrationJournalStage.OriginalRestored;
            return from==SpatialMigrationJournalStage.DurableVerified&&(to==SpatialMigrationJournalStage.Finalized||to==SpatialMigrationJournalStage.OriginalRestored);
        }
        private static void Validate(SpatialMigrationJournal j,SpatialSerializedInputLimits limits,IList<SpatialContractIssue> x)
        {
            if(j==null||j.JournalSchemaVersion!=SpatialMigrationContractIdentity.JournalSchemaVersion){x.Add(SpatialContractIssue.InvalidIdentity);return;}if(!Enum.IsDefined(typeof(SpatialMigrationJournalStage),j.Stage)){x.Add(SpatialContractIssue.InvalidStage);return;}var d=SpatialMigrationDescriptorContracts.Serialize(j.Descriptor,limits);if(!d.IsValid){x.Add(SpatialContractIssue.InvalidField);return;}string fp=SpatialContractSha256.Compute(d.Value),identity=SpatialMigrationTransactionIdentity.ComputeIdentity(j.Descriptor.OriginalPayloadSha256,fp),tid=SpatialMigrationTransactionIdentity.CreateTransactionId(identity);
            if(!string.Equals(fp,j.DescriptorFingerprintSha256,StringComparison.Ordinal)||!string.Equals(identity,j.TransactionIdentitySha256,StringComparison.Ordinal)||!string.Equals(tid,j.TransactionId,StringComparison.Ordinal)||!string.Equals(j.Descriptor.OriginalPayloadSha256,j.OriginalPayloadSha256,StringComparison.Ordinal))x.Add(SpatialContractIssue.InvalidIdentity);
            string suffix="."+j.TransactionId+".journal.json";string stem=j.RelativeJournalFilename!=null&&j.RelativeJournalFilename.EndsWith(suffix,StringComparison.Ordinal)?j.RelativeJournalFilename.Substring(0,j.RelativeJournalFilename.Length-suffix.Length):string.Empty;string journal=stem+suffix,string backupName=stem+"."+j.TransactionId+".original.bak",candidateName=stem+"."+j.TransactionId+".candidate.tmp",receiptName=stem+"."+j.TransactionId+".finalized";if(stem.Length==0||stem.Length>SpatialMigrationSidecarPaths.MaximumStemCharacters||journal!=j.RelativeJournalFilename||backupName!=j.RelativeOriginalBackupFilename||candidateName!=j.RelativeCandidateStagingFilename||(j.RelativeFinalizedReceiptFilename!=null&&receiptName!=j.RelativeFinalizedReceiptFilename)||!SpatialMigrationSidecarPaths.ValidRelative(journal,SpatialMigrationSidecarPaths.MaximumGeneratedFilenameCharacters))x.Add(SpatialContractIssue.InvalidPath);
            bool backup=j.Stage!=SpatialMigrationJournalStage.DescriptorPinned;bool candidate=j.Stage==SpatialMigrationJournalStage.CandidateVerified||j.Stage==SpatialMigrationJournalStage.Replaced||j.Stage==SpatialMigrationJournalStage.DurableVerified||j.Stage==SpatialMigrationJournalStage.Finalized;
            if(backup?!SpatialContractSha256.IsCanonical(j.BackupPayloadSha256)||j.BackupPayloadSha256!=j.OriginalPayloadSha256:j.BackupPayloadSha256!=null)x.Add(SpatialContractIssue.InvalidStageData);if(candidate?!SpatialContractSha256.IsCanonical(j.ExpectedCandidateSha256):j.ExpectedCandidateSha256!=null)x.Add(SpatialContractIssue.InvalidStageData);
            bool receiptAllowed=j.Stage==SpatialMigrationJournalStage.DurableVerified||j.Stage==SpatialMigrationJournalStage.Finalized;if(!receiptAllowed&&j.RelativeFinalizedReceiptFilename!=null)x.Add(SpatialContractIssue.InvalidStageData);foreach(string h in new[]{j.DescriptorFingerprintSha256,j.TransactionIdentitySha256,j.OriginalPayloadSha256})if(!SpatialContractSha256.IsCanonical(h))x.Add(SpatialContractIssue.InvalidHash);
        }
        private static void AddS(StringBuilder b,string n,string v){b.Append(',');ContractJson.String(b,n);b.Append(':');ContractJson.String(b,v);}private static void AddNullable(StringBuilder b,string n,string v){b.Append(',');ContractJson.String(b,n);b.Append(':');if(v==null)b.Append("null");else ContractJson.String(b,v);}private static void AddI(StringBuilder b,string n,int v,bool first=false){if(!first)b.Append(',');ContractJson.String(b,n);b.Append(':').Append(v.ToString(CultureInfo.InvariantCulture));}
    }
}
